### ISSUE TITLE
What about an `oxford` option?

### ISSUE THREAD

**Issue by zeke** [ljharb/listify#3]
This is just silly, but maybe worth adding for fun:

``` js
assert(listify([1, 2, 3]) === '1, 2, and 3'); // default to true
assert(listify([1, 2, 3], {oxford: false}) === '1, 2 and 3');
```

As a lover of Oxford commas (AKA [serial commas](https://en.wikipedia.org/wiki/Serial_comma)), I personally wouldn't use this feature, but [others might](https://www.youtube.com/watch?v=P_i1xk07o4g).

**Comment by ljharb** [comment]
See https://twitter.com/ljharb/status/596364931131256833 and https://github.com/ljharb/listify/pull/2#issuecomment-99943293 :-)

**Comment by zeke** [comment]
ha
